### ISSUE TITLE
Delayed phasing/connecting issues

### ISSUE THREAD

**Issue by sharpzy** [pvpworldrepo/PVPWorld#1]
I've had issues with phasing into new areas and seeing players/objects as well as a delay in retrieving the character select screen.  Sometimes it gets stuck on the "connected" button and I have to hit cancel and refresh the character selection screen for it to load.

**Comment by dencelle** [comment]
I believe this should be fixed in our most recent update. i've done a lot of optimizations to the servers base code and its dependencies, as more gets fixed, these kind of things should slowly fix themselfs
